#import <WebGPU/GPUAdapter.idl>
#import <WebGPU/GPUTexture.idl>
#import <WebGPU/WGSLLanguageFeatures.idl>


// https://www.w3.org/TR/webgpu/#gpu-interface
[Exposed=(Window,Worker), SecureContext]
interface GPU {
    Promise<GPUAdapter?> requestAdapter(optional GPURequestAdapterOptions options = {});
    GPUTextureFormat getPreferredCanvasFormat();
    [SameObject] readonly attribute WGSLLanguageFeatures wgslLanguageFeatures;
};
