// https://www.w3.org/TR/webgpu/#typedefdef-gpusize64
typedef [EnforceRange] unsigned long long GPUSize64;

// https://www.w3.org/TR/webgpu/#typedefdef-gpusize64out
typedef unsigned long long GPUSize64Out;

// https://www.w3.org/TR/webgpu/#typedefdef-gpuflagsconstant
typedef unsigned long GPUFlagsConstant;

// https://www.w3.org/TR/webgpu/#dictdef-gpuobjectdescriptorbase
dictionary GPUObjectDescriptorBase {
    USVString label = "";
};

// https://www.w3.org/TR/webgpu/#gpuobjectbase
interface mixin GPUObjectBase {
    attribute USVString label;
};
