#import <WebGPU/GPUObjectBase.idl>
#import <WebGPU/GPUTextureView.idl>

// https://www.w3.org/TR/webgpu/#typedefdef-gpucolor
dictionary GPUColorDict {
    required double r;
    required double g;
    required double b;
    required double a;
};
typedef (sequence<double> or GPUColorDict) GPUColor;

// https://www.w3.org/TR/webgpu/#enumdef-gpuloadop
enum GPULoadOp {
    "load",
    "clear",
};

// https://www.w3.org/TR/webgpu/#enumdef-gpustoreop
enum GPUStoreOp {
    "store",
    "discard",
};

// https://www.w3.org/TR/webgpu/#dictdef-gpurenderpasscolorattachment
dictionary GPURenderPassColorAttachment {
    // FIXME: required (GPUTexture or GPUTextureView) view;
    required GPUTextureView view;
    // FIXME: GPUIntegerCoordinate depthSlice;
    // FIXME: (GPUTexture or GPUTextureView) resolveTarget;

    GPUColor clearValue;
    required GPULoadOp loadOp;
    required GPUStoreOp storeOp;
};

// https://www.w3.org/TR/webgpu/#dictdef-gpurenderpassdescriptor
dictionary GPURenderPassDescriptor
         : GPUObjectDescriptorBase {
    // FIXME: Support ? entries in a sequence
    required sequence<GPURenderPassColorAttachment> colorAttachments;
};

// https://www.w3.org/TR/webgpu/#gpurendercommandsmixin
interface mixin GPURenderCommandsMixin {
    undefined setPipeline(GPURenderPipeline pipeline);

    // FIXME: undefined setIndexBuffer(GPUBuffer buffer, GPUIndexFormat indexFormat, optional GPUSize64 offset = 0, optional GPUSize64 size);
    // FIXME: undefined setVertexBuffer(GPUIndex32 slot, GPUBuffer? buffer, optional GPUSize64 offset = 0, optional GPUSize64 size);

    undefined draw(GPUSize32 vertexCount, optional GPUSize32 instanceCount = 1, optional GPUSize32 firstVertex = 0, optional GPUSize32 firstInstance = 0);
    // FIXME: undefined drawIndexed(GPUSize32 indexCount, optional GPUSize32 instanceCount = 1, optional GPUSize32 firstIndex = 0, optional GPUSignedOffset32 baseVertex = 0, optional GPUSize32 firstInstance = 0);

    // FIXME: undefined drawIndirect(GPUBuffer indirectBuffer, GPUSize64 indirectOffset);
    // FIXME: undefined drawIndexedIndirect(GPUBuffer indirectBuffer, GPUSize64 indirectOffset);
};

// https://www.w3.org/TR/webgpu/#gpurenderpassencoder
[Exposed=(Window, Worker), SecureContext]
interface GPURenderPassEncoder {
    // FIXME: Implement remaining methods
    undefined end();
};
GPURenderPassEncoder includes GPUObjectBase;
GPURenderPassEncoder includes GPURenderCommandsMixin;
// FIXME: Include remaining interfaces
