// https://www.w3.org/TR/webgpu/#type-definitions

// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpubufferdynamicoffset
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpustencilvalue
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpudepthbias
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpusize64

// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpuintegercoordinate
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpuindex32
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpusize32
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpusignedoffset32

// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpusize64out
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpuintegercoordinateout
// FIXME: https://www.w3.org/TR/webgpu/#typedefdef-gpusize32out

// https://www.w3.org/TR/webgpu/#typedefdef-gpuflagsconstant
typedef unsigned long GPUFlagsConstant;
